name: enfo
description: Enfo, a minimalistic pomodoro timer for distracted people.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  adaptive_theme: 3.7.2
  shared_preferences: ^2.5.5
  local_notifier: ^0.1.6
  window_manager: ^0.5.2
  flutter_local_notifications: ^22.3.1
  permission_handler: ^13.0.2
  url_launcher: ^6.3.2
  google_mobile_ads: ^9.1.0
  wakelock_plus: ^1.8.0
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700