/// One bundled song. All of them come from collections with a verified
/// license (Wikimedia Commons and the Open Lo-Fi CC0 release); see
/// assets/music/CREDITS.md.
class MusicTrack {
  const MusicTrack({
    required this.asset,
    required this.title,
    required this.artist,
    required this.seconds,
    required this.license,
    required this.licenseUrl,
    required this.source,
  });

  final String asset;
  final String title;
  final String artist;
  final int seconds;

  /// Short license name, e.g. `CC0` or `CC BY 4.0`.
  final String license;
  final String licenseUrl;

  /// Where the song was published (its Commons page or release repository).
  final String source;

  /// CC BY needs the artist credited wherever the song is used.
  bool get needsCredit => license != 'CC0';
}

/// Lo-fi / chill songs bundled with the app (about 3 hours, ~67 MB, Ogg
/// Vorbis). The Open Lo-Fi tracks are mono 32 kHz at q0 after a deliberate
/// lo-fi chain (9.5 kHz low-pass, soft saturation, tape wow and a whisper of
/// pink-noise hiss). CC0 first, then CC BY.
const List<MusicTrack> musicCatalog = [
  MusicTrack(
    asset: 'assets/music/01_chill_beat.ogg',
    title: 'Chill Beat',
    artist: 'Maddy',
    seconds: 96,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Chill_Beat.ogg',
  ),
  MusicTrack(
    asset:
        'assets/music/02_kuromaru_ft_hereafter_laxin_lo_fi_background_music.ogg',
    title: '’laxin',
    artist: 'Kuromaru',
    seconds: 104,
    license: 'CC BY 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
    source:
        'https://commons.wikimedia.org/wiki/File:Kuromaru_ft_.hereafter_-_%E2%80%99laxin_(Lo_Fi_Background_Music).ogg',
  ),
  MusicTrack(
    asset: 'assets/music/03_lofi_music_001.ogg',
    title: 'Lofi 001',
    artist: 'Luisalvaz',
    seconds: 166,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Lofi_music_001.wav',
  ),
  MusicTrack(
    asset: 'assets/music/04_loyalty_freak_music_01_sweet_you.ogg',
    title: 'Sweet You',
    artist: 'Loyalty Freak Music',
    seconds: 160,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_01_-_Sweet_You.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/05_loyalty_freak_music_02_old_saga.ogg',
    title: 'Old Saga',
    artist: 'Loyalty Freak Music',
    seconds: 150,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_02_-_Old_Saga.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/06_loyalty_freak_music_06_softly.ogg',
    title: 'Softly',
    artist: 'Loyalty Freak Music',
    seconds: 262,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_06_-_Softly.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/07_loyalty_freak_music_08_beach.ogg',
    title: 'Beach',
    artist: 'Loyalty Freak Music',
    seconds: 161,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_08_-_Beach.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/08_loyalty_freak_music_09_shoepop.ogg',
    title: 'Shoepop',
    artist: 'Loyalty Freak Music',
    seconds: 164,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_09_-_Shoepop.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/09_loyalty_freak_music_10_hangover.ogg',
    title: 'Hangover',
    artist: 'Loyalty Freak Music',
    seconds: 193,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_10_-_Hangover.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/10_loyalty_freak_music_11_standing.ogg',
    title: 'Standing',
    artist: 'Loyalty Freak Music',
    seconds: 161,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_11_-_Standing.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/11_loyalty_freak_music_13_work.ogg',
    title: 'Work',
    artist: 'Loyalty Freak Music',
    seconds: 145,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
        'https://commons.wikimedia.org/wiki/File:Loyalty_Freak_Music_-_13_-_Work.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/12_raspberrymusic_lofi_hip_hop_upbeat.ogg',
    title: 'Lofi Hip Hop Upbeat',
    artist: 'raspberrymusic',
    seconds: 134,
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    source:
        'https://commons.wikimedia.org/wiki/File:Raspberrymusic_-_Lofi_Hip_Hop_Upbeat.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/13_sappheiros_perspective_lofi_hip_hop.ogg',
    title: 'Perspective',
    artist: 'Sappheiros',
    seconds: 137,
    license: 'CC BY 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
    source:
        'https://commons.wikimedia.org/wiki/File:Sappheiros_-_Perspective_(Lofi_Hip_Hop).ogg',
  ),
  MusicTrack(
    asset: 'assets/music/14_study_and_relax_by_kevin_macleod.ogg',
    title: 'Study And Relax',
    artist: 'Kevin MacLeod',
    seconds: 223,
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    source:
        'https://commons.wikimedia.org/wiki/File:Study_And_Relax_by_Kevin_MacLeod.ogg',
  ),
  MusicTrack(
    asset: 'assets/music/15_2_am_debug_loop.ogg',
    title: '2 AM Debug Loop',
    artist: 'Open Lo-Fi',
    seconds: 118,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/16_brushstrokes_and_rain.ogg',
    title: 'Brushstrokes and Rain',
    artist: 'Open Lo-Fi',
    seconds: 146,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/17_chapter_by_lamplight.ogg',
    title: 'Chapter By Lamplight',
    artist: 'Open Lo-Fi',
    seconds: 136,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/18_coffee_ring_notebook.ogg',
    title: 'Coffee Ring Notebook',
    artist: 'Open Lo-Fi',
    seconds: 131,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/19_cursor_after_midnight.ogg',
    title: 'Cursor After Midnight',
    artist: 'Open Lo-Fi',
    seconds: 232,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/20_dog_eared_pages.ogg',
    title: 'Dog Eared Pages',
    artist: 'Open Lo-Fi',
    seconds: 168,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/21_dust_in_the_curtains.ogg',
    title: 'Dust in the Curtains',
    artist: 'Open Lo-Fi',
    seconds: 186,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/22_first_coffee_thoughts.ogg',
    title: 'First Coffee Thoughts',
    artist: 'Open Lo-Fi',
    seconds: 95,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/23_graphite_mornings.ogg',
    title: 'Graphite Mornings',
    artist: 'Open Lo-Fi',
    seconds: 130,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/24_hour_between_clicks.ogg',
    title: 'Hour Between Clicks',
    artist: 'Open Lo-Fi',
    seconds: 224,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/25_kettle_before_work.ogg',
    title: 'Kettle Before Work',
    artist: 'Open Lo-Fi',
    seconds: 147,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/26_margin_notes_at_dusk.ogg',
    title: 'Margin Notes at Dusk',
    artist: 'Open Lo-Fi',
    seconds: 135,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/27_morning_pages.ogg',
    title: 'Morning Pages',
    artist: 'Open Lo-Fi',
    seconds: 133,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/28_penciled_sunbeams.ogg',
    title: 'Penciled Sunbeams',
    artist: 'Open Lo-Fi',
    seconds: 121,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/29_quiet_lungs_quiet_light.ogg',
    title: 'Quiet Lungs Quiet Light',
    artist: 'Open Lo-Fi',
    seconds: 151,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/30_stacks_of_quiet_hours.ogg',
    title: 'Stacks of Quiet Hours',
    artist: 'Open Lo-Fi',
    seconds: 140,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/31_sunrise_stretch_flow.ogg',
    title: 'Sunrise Stretch Flow',
    artist: 'Open Lo-Fi',
    seconds: 189,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/32_watercolors_by_the_window.ogg',
    title: 'Watercolors By the Window',
    artist: 'Open Lo-Fi',
    seconds: 117,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/33_almost_floating.ogg',
    title: 'Almost Floating',
    artist: 'Open Lo-Fi',
    seconds: 202,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/34_aurora_on_mute.ogg',
    title: 'Aurora on Mute',
    artist: 'Open Lo-Fi',
    seconds: 178,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/35_blue_below_the_surface.ogg',
    title: 'Blue Below the Surface',
    artist: 'Open Lo-Fi',
    seconds: 178,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/36_drifting_through_fog.ogg',
    title: 'Drifting Through Fog',
    artist: 'Open Lo-Fi',
    seconds: 185,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/37_first_light_on_the_ridge.ogg',
    title: 'First Light on the Ridge',
    artist: 'Open Lo-Fi',
    seconds: 158,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/38_glasshouse_ghosts.ogg',
    title: 'Glasshouse Ghosts',
    artist: 'Open Lo-Fi',
    seconds: 173,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/39_green_after_midnight.ogg',
    title: 'Green After Midnight',
    artist: 'Open Lo-Fi',
    seconds: 185,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/40_moonlit_moss.ogg',
    title: 'Moonlit Moss',
    artist: 'Open Lo-Fi',
    seconds: 153,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/41_orbiting_in_silence.ogg',
    title: 'Orbiting in Silence',
    artist: 'Open Lo-Fi',
    seconds: 159,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/42_satellite_lullaby.ogg',
    title: 'Satellite Lullaby',
    artist: 'Open Lo-Fi',
    seconds: 125,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/43_tide_pools_at_twilight.ogg',
    title: 'Tide Pools at Twilight',
    artist: 'Open Lo-Fi',
    seconds: 190,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/44_warm_constellations.ogg',
    title: 'Warm Constellations',
    artist: 'Open Lo-Fi',
    seconds: 112,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/45_dusk_between_stoops.ogg',
    title: 'Dusk Between Stoops',
    artist: 'Open Lo-Fi',
    seconds: 132,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/46_dust_on_the_morning_keys.ogg',
    title: 'Dust on the Morning Keys',
    artist: 'Open Lo-Fi',
    seconds: 153,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/47_glow_on_the_overpass.ogg',
    title: 'Glow on the Overpass',
    artist: 'Open Lo-Fi',
    seconds: 160,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/48_porchlight_golden_hour.ogg',
    title: 'Porchlight Golden Hour',
    artist: 'Open Lo-Fi',
    seconds: 130,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/49_sidewalk_slow_jam.ogg',
    title: 'Sidewalk Slow Jam',
    artist: 'Open Lo-Fi',
    seconds: 135,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/50_soft_gold_sky.ogg',
    title: 'Soft Gold Sky',
    artist: 'Open Lo-Fi',
    seconds: 143,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/51_sunset_offbeat.ogg',
    title: 'Sunset Offbeat',
    artist: 'Open Lo-Fi',
    seconds: 159,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/52_window_seat_daydream.ogg',
    title: 'Window Seat Daydream',
    artist: 'Open Lo-Fi',
    seconds: 140,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/53_ashes_in_the_coffee_cup.ogg',
    title: 'Ashes in the Coffee Cup',
    artist: 'Open Lo-Fi',
    seconds: 132,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/54_breezy_afternoon_terrace.ogg',
    title: 'Breezy Afternoon Terrace',
    artist: 'Open Lo-Fi',
    seconds: 90,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/55_candlelit_at_70_bpm.ogg',
    title: 'Candlelit at 70 BPM',
    artist: 'Open Lo-Fi',
    seconds: 122,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/56_dust_and_hardcovers.ogg',
    title: 'Dust and Hardcovers',
    artist: 'Open Lo-Fi',
    seconds: 212,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/57_harbor_before_words.ogg',
    title: 'Harbor Before Words',
    artist: 'Open Lo-Fi',
    seconds: 146,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/58_last_call_in_c_minor.ogg',
    title: 'Last Call in C Minor',
    artist: 'Open Lo-Fi',
    seconds: 138,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/59_linen_and_limoncello.ogg',
    title: 'Linen and Limoncello',
    artist: 'Open Lo-Fi',
    seconds: 115,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/60_midnight_amber_room.ogg',
    title: 'Midnight Amber Room',
    artist: 'Open Lo-Fi',
    seconds: 145,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/61_rain_on_the_boulevard.ogg',
    title: 'Rain on the Boulevard',
    artist: 'Open Lo-Fi',
    seconds: 90,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/62_saxophone_in_the_rain.ogg',
    title: 'Saxophone in the Rain',
    artist: 'Open Lo-Fi',
    seconds: 99,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/63_stacks_of_quiet_books.ogg',
    title: 'Stacks of Quiet Books',
    artist: 'Open Lo-Fi',
    seconds: 180,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/64_velvet_cigarette_haze.ogg',
    title: 'Velvet Cigarette Haze',
    artist: 'Open Lo-Fi',
    seconds: 152,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/65_bamboo_shadow_waltz.ogg',
    title: 'Bamboo Shadow Waltz',
    artist: 'Open Lo-Fi',
    seconds: 162,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/66_bells_before_sunrise.ogg',
    title: 'Bells Before Sunrise',
    artist: 'Open Lo-Fi',
    seconds: 140,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/67_teacup_morning_fog.ogg',
    title: 'Teacup Morning Fog',
    artist: 'Open Lo-Fi',
    seconds: 139,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/68_temple_at_dawn.ogg',
    title: 'Temple at Dawn',
    artist: 'Open Lo-Fi',
    seconds: 114,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/69_3_am_echoes.ogg',
    title: '3 AM Echoes',
    artist: 'Open Lo-Fi',
    seconds: 97,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/70_electric_puddles.ogg',
    title: 'Electric Puddles',
    artist: 'Open Lo-Fi',
    seconds: 140,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/71_rain_off_the_neon_signs.ogg',
    title: 'Rain Off the Neon Signs',
    artist: 'Open Lo-Fi',
    seconds: 118,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
  MusicTrack(
    asset: 'assets/music/72_streetlights_in_the_rearview.ogg',
    title: 'Streetlights in the Rearview',
    artist: 'Open Lo-Fi',
    seconds: 135,
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://github.com/btahir/open-lofi',
  ),
];
