import 'package:flutter/material.dart';

import '../../l10n/gen/app_localizations.dart';
import 'clock_style.dart';

/// Curated pairing of a clock style with an accent color, applied together
/// in one tap.
enum ClockCombo {
  deepFocus(ClockStyle.orbit, Colors.indigo),
  mint(ClockStyle.wavyRing, Colors.teal),
  sunset(ClockStyle.liquid, Colors.deepOrange),
  zen(ClockStyle.breathe, Colors.blueGrey),
  tomato(ClockStyle.tomato, Colors.red),
  night(ClockStyle.digits, Colors.deepPurple),
  playful(ClockStyle.cookie, Colors.pink),
  minimal(ClockStyle.minutes, Colors.cyan),
  arcade(ClockStyle.matrix, Colors.green),
  calculator(ClockStyle.sevenSeg, Colors.lightGreen),
  departures(ClockStyle.flip, Colors.amber),
  candlelight(ClockStyle.candle, Colors.orange),
  moonlight(ClockStyle.moon, Color(0xFF334155)),
  garden(ClockStyle.flower, Color(0xFFD946EF)),
  summer(ClockStyle.sun, Colors.amber),
  workshop(ClockStyle.gears, Color(0xFF64748B)),
  fizzy(ClockStyle.bubbles, Colors.lightBlue),
  sunfield(ClockStyle.sunflower, Color(0xFFF59E0B)),
  summerNight(ClockStyle.fireflies, Color(0xFF84CC16)),
  hypnosis(ClockStyle.pendulum, Color(0xFF6366F1)),
  bouncy(ClockStyle.bounce, Color(0xFFF43F5E)),
  shapeshifter(ClockStyle.morph, Color(0xFF7C3AED)),
  lava(ClockStyle.blob, Color(0xFFEA580C)),
  ocean(ClockStyle.wavyBar, Color(0xFF0EA5E9)),
  pulse(ClockStyle.equalizer, Color(0xFFE11D48)),
  pond(ClockStyle.ripple, Color(0xFF14B8A6)),
  espresso(ClockStyle.battery, Colors.brown),
  speedometer(ClockStyle.gauge, Colors.red),
  compass(ClockStyle.needle, Color(0xFF2563EB)),
  classicClock(ClockStyle.analog, Colors.blueGrey),
  concentric(ClockStyle.rings, Color(0xFF10B981)),
  rounded(ClockStyle.squircle, Colors.lightBlue),
  signal(ClockStyle.columns, Colors.green),
  thermometer(ClockStyle.vertical, Colors.deepOrange),
  milestones(ClockStyle.steps, Colors.teal),
  retroBlocks(ClockStyle.blocks, Colors.purple),
  hypnoSpiral(ClockStyle.spiral, Colors.pink),
  citrus(ClockStyle.slices, Colors.orange),
  chocolate(ClockStyle.pills, Color(0xFF8B5E3C)),
  crystal(ClockStyle.hexagon, Colors.cyan),
  staircase(ClockStyle.stairs, Colors.indigo),
  tapeMeasure(ClockStyle.ruler, Colors.lime),
  boldType(ClockStyle.fill, Colors.deepPurple),
  pill(ClockStyle.capsule, Colors.pink),
  slotMachine(ClockStyle.rollers, Colors.amber),
  whisper(ClockStyle.fine, Colors.blueGrey),
  deadline(ClockStyle.endTime, Colors.deepOrange),
  percentage(ClockStyle.percent, Colors.green),
  stopwatch(ClockStyle.seconds, Colors.cyan),
  skyscraper(ClockStyle.tall, Colors.blueGrey),
  waveText(ClockStyle.wobble, Colors.lightBlue),
  dashboard(ClockStyle.labeled, Colors.indigo),
  exponent(ClockStyle.superscript, Colors.teal),
  grandmaKitchen(ClockStyle.kitchen, Colors.orange),
  cyber(ClockStyle.segments, Color(0xFF14B8A6)),
  candy(ClockStyle.tiles, Colors.pink),
  confetti(ClockStyle.dots, Color(0xFFF43F5E)),
  cookieJar(ClockStyle.cookie, Colors.brown),
  sandbox(ClockStyle.hourglass, Colors.amber),
  pizzaNight(ClockStyle.pie, Colors.deepOrange);

  const ClockCombo(this.style, this.color);

  final ClockStyle style;
  final Color color;

  String labelOf(AppLocalizations l) => switch (this) {
        ClockCombo.deepFocus => l.comboDeepFocus,
        ClockCombo.mint => l.comboMint,
        ClockCombo.sunset => l.comboSunset,
        ClockCombo.zen => l.comboZen,
        ClockCombo.tomato => l.comboTomato,
        ClockCombo.night => l.comboNight,
        ClockCombo.playful => l.comboPlayful,
        ClockCombo.minimal => l.comboMinimal,
        ClockCombo.arcade => l.comboArcade,
        ClockCombo.calculator => l.comboCalculator,
        ClockCombo.departures => l.comboDepartures,
        ClockCombo.candlelight => l.comboCandlelight,
        ClockCombo.moonlight => l.comboMoonlight,
        ClockCombo.garden => l.comboGarden,
        ClockCombo.summer => l.comboSummer,
        ClockCombo.workshop => l.comboWorkshop,
        ClockCombo.fizzy => l.comboFizzy,
        ClockCombo.sunfield => l.comboSunfield,
        ClockCombo.summerNight => l.comboSummerNight,
        ClockCombo.hypnosis => l.comboHypnosis,
        ClockCombo.bouncy => l.comboBouncy,
        ClockCombo.shapeshifter => l.comboShapeshifter,
        ClockCombo.lava => l.comboLava,
        ClockCombo.ocean => l.comboOcean,
        ClockCombo.pulse => l.comboPulse,
        ClockCombo.pond => l.comboPond,
        ClockCombo.espresso => l.comboEspresso,
        ClockCombo.speedometer => l.comboSpeedometer,
        ClockCombo.compass => l.comboCompass,
        ClockCombo.classicClock => l.comboClassicClock,
        ClockCombo.concentric => l.comboConcentric,
        ClockCombo.rounded => l.comboRounded,
        ClockCombo.signal => l.comboSignal,
        ClockCombo.thermometer => l.comboThermometer,
        ClockCombo.milestones => l.comboMilestones,
        ClockCombo.retroBlocks => l.comboRetroBlocks,
        ClockCombo.hypnoSpiral => l.comboHypnoSpiral,
        ClockCombo.citrus => l.comboCitrus,
        ClockCombo.chocolate => l.comboChocolate,
        ClockCombo.crystal => l.comboCrystal,
        ClockCombo.staircase => l.comboStaircase,
        ClockCombo.tapeMeasure => l.comboTapeMeasure,
        ClockCombo.boldType => l.comboBoldType,
        ClockCombo.pill => l.comboPill,
        ClockCombo.slotMachine => l.comboSlotMachine,
        ClockCombo.whisper => l.comboWhisper,
        ClockCombo.deadline => l.comboDeadline,
        ClockCombo.percentage => l.comboPercentage,
        ClockCombo.stopwatch => l.comboStopwatch,
        ClockCombo.skyscraper => l.comboSkyscraper,
        ClockCombo.waveText => l.comboWaveText,
        ClockCombo.dashboard => l.comboDashboard,
        ClockCombo.exponent => l.comboExponent,
        ClockCombo.grandmaKitchen => l.comboGrandmaKitchen,
        ClockCombo.cyber => l.comboCyber,
        ClockCombo.candy => l.comboCandy,
        ClockCombo.confetti => l.comboConfetti,
        ClockCombo.cookieJar => l.comboCookieJar,
        ClockCombo.sandbox => l.comboSandbox,
        ClockCombo.pizzaNight => l.comboPizzaNight,
      };
}
